pipeline {
    agent any

    environment {
        PROJECT_DIR = 'presence-app-main/presence-app-main'
        BUILD_DIR = 'presence-app-main/presence-app-main/.next'
        DEPLOY_DIR = 'C:\\deploy\\presence-app'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir("${PROJECT_DIR}") {
                    bat 'npm install --legacy-peer-deps'
                }
            }
        }

        stage('Build') {
            steps {
                dir("${PROJECT_DIR}") {
                    bat 'npm run build'
                }
            }
        }

        stage('Debug List .next folder') {
            steps {
                // Liste tous les fichiers et dossiers dans .next
                bat "dir \"${BUILD_DIR}\" /a /s"
            }
        }

        stage('Deploy') {
            steps {
                bat "if exist \"${DEPLOY_DIR}\" rmdir /s /q \"${DEPLOY_DIR}\""
                bat "mkdir \"${DEPLOY_DIR}\""

                // Utilisation de PowerShell pour copier récursivement tout le contenu
                bat """
                powershell -command "Copy-Item -Path '${BUILD_DIR}\\\\*' -Destination '${DEPLOY_DIR}' -Recurse -Force"
                """
            }
        }
    }

    post {
        success {
            echo '✅ Déploiement terminé avec succès.'
        }
        failure {
            echo '❌ Échec du pipeline.'
        }
    }
}
