pipeline {
    agent any

    environment {
        PROJECT_DIR = 'presence-app-main/presence-app-main'
        BUILD_DIR = 'presence-app-main\\presence-app-main\\.next'
        DEPLOY_DIR = 'C:\\deploy\\presence-app'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir("${env.PROJECT_DIR}") {
                    bat 'npm install --legacy-peer-deps'
                }
            }
        }

        stage('Build') {
            steps {
                dir("${env.PROJECT_DIR}") {
                    bat 'npm run build'
                }
            }
        }

        stage('Deploy') {
            steps {
                // Supprimer le dossier de déploiement s'il existe
                bat "if exist \"${env.DEPLOY_DIR}\" rmdir /s /q \"${env.DEPLOY_DIR}\""
                // Créer le dossier de déploiement
                bat "mkdir \"${env.DEPLOY_DIR}\""
                // Copier les fichiers du build
                bat "xcopy /s /e /y \"${env.BUILD_DIR}\\*\" \"${env.DEPLOY_DIR}\\\""
            }
        }
        stage('Verify Build Directory') {
            steps {
                bat "dir \"${env.BUILD_DIR}\""
    }
}

    }

    post {
        success {
            echo '✅ Déploiement terminé avec succès.'
        }
        failure {
            echo '❌ Échec du pipeline.'
        }
    }
}
